# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2
# Mod Properties
mod_version=0.0.1
maven_group=com.panita
archives_base_name=enriquecraft
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.161.0+26.3
placeholder_api_version=3.2.0+26.3
permissions_api_version=0.7.0
junit_version=5.14.4
